language: python

python:
  - '3.6'
  - '2.7'

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - nosetests  --with-coverage --cover-package=iot_analytics

after_success:
  - coveralls
